logging:
  level:
    codefun: INFO
    root: INFO

app:
  # the  server
  backend-host: localhost
  backend-port: 8081
  web-socket-path: /ws_bin
  log-data: false
  local-port: 8088
#  local-addr: 172.25.66.221
  local-addr: localhost
