logging:
  level:
    codefun: DEBUG
    root: INFO

spring:
  web:
    resources:
      static-locations: classpath:/static/

  mvc:
    static-path-pattern: /mystatic/**

app:
  # the  server
  host: 172.25.66.221
  port: 8081
  message: .
  user-count: 100

