logging:
  level:
    codefun: INFO
    root: INFO

app:
  # user 相关
  user-count: 100
  ramp-up-time: 10

  # 消息相关
  # message: .
  # message-file:
  message-interval-ms: 200
  wait-to-reconnect-ms: 10000
  # bytes total = send-int-count*8
  send-int-count: 100
  log-stat-interval-ms: 10000
  remote-address: ws://localhost:8088/ws_bin
