logging:
  level:
    codefun: INFO
    root: INFO

app:
  # user 相关
  user-count: 1000
  ramp-up-time: 100

  # 消息相关
  # message: .
  # message-file:
  message-interval-ms: 100
  wait-to-reconnect-ms: 10000
  # bytes total = send-int-count*8
  send-int-count: 1000
  log-stat-interval-ms: 10000
  remote-address: localhost:8088
