server:
  port: 8088

logging:
  level:
    codefun: INFO
    root: INFO

spring:
  web:
    resources:
      static-locations: classpath:/static/

  mvc:
    static-path-pattern: /mystatic/**

app:
  # the  server
  backend-host: localhost
  backend-port: 8081


